theme="gruvbox"

[editor]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding"]

[editor.file-picker]
hidden = false
git-ignore = false

[keys.normal]
a = ["append_mode", "collapse_selection"]
i = ["insert_mode", "collapse_selection"]
# C-g = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80% -E lazygit"
